### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by ezawadzki** [zmts/beauty-vuejs-boilerplate#44]
Hi,

Just to let you know that I tried to install and compiled and it failed :

```
 v1 git:(master) npm install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

audited 1481 packages in 6.223s

48 packages are looking for funding
  run `npm fund` for details

found 931 vulnerabilities (392 low, 197 moderate, 342 high)
  run `npm audit fix` to fix them, or `npm audit` for details


   ╭────────────────────────────────────────────────────────────────╮
   │                                                                │
   │      New major version of npm available! 6.14.10 → 7.20.5      │
   │   Changelog: https://github.com/npm/cli/releases/tag/v7.20.5   │
   │               Run npm install -g npm to update!                │
   │                                                                │
   ╰────────────────────────────────────────────────────────────────╯

```

```
v1 git:(master) npm run serve

> beauty-vuejs-boilerplate@1.0.0 serve /home/emilie/Devel/FREELANCE/Magali/v1
> NODE_ENV=development vue-cli-service serve

 INFO  Starting development server...
11% building 14/15 modules 1 active ...nt-loader/index.js??ref--13-0!/home/emilie/Devel/FREELANCE/Magali/v1/src/main.jsBrowserslist: caniuse-lite is outdated. Please run the following command: `npm update`
98% after emitting CopyPlugin

 ERROR  Failed to compile with 1 errors                                                                      11:42:06 AM

 error  in ./src/main.js

Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: [BABEL] /home/emilie/Devel/FREELANCE/Magali/v1/src/main.js: Cannot find module '/home/emilie/Devel/FREELANCE/Magali/v1/node_modules/@babel/compat-data/data/corejs3-shipped-proposals' (While processing: "/home/emilie/Devel/FREELANCE/Magali/v1/node_modules/@vue/cli-plugin-babel/preset.js")
    at createEsmNotFoundErr (internal/modules/cjs/loader.js:842:15)
    at finalizeEsmResolution (internal/modules/cjs/loader.js:835:15)
    at resolveExports (internal/modules/cjs/loader.js:424:14)
    at Function.Module._findPath (internal/modules/cjs/loader.js:464:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:802:27)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/emilie/Devel/FREELANCE/Magali/v1/node_modules/@babel/preset-env/lib/polyfills/corejs3/usage-plugin.js:10:55)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/emilie/Devel/FREELANCE/Magali/v1/node_modules/@babel/preset-env/lib/index.js:29:44)

 @ multi (webpack)-dev-server/client?http://172.28.153.21:8080/sockjs-node (webpack)/hot/dev-server.js ./src/main.js
```

**Comment by Aniruddh-J** [comment]
Add this to your devDependencies in `package.json`

`"@babel/compat-data": "7.9.0"`
